// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: attachment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Attachment_PlainText
	//	*Attachment_ExecutedShellCommand
	//	*Attachment_RunningShellCommand
	//	*Attachment_DriveObject
	//	*Attachment_DiffHunk
	//	*Attachment_DiffSet
	//	*Attachment_DocumentContent
	//	*Attachment_FilePathReference
	Value         isAttachment_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetValue() isAttachment_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attachment) GetPlainText() string {
	if x != nil {
		if x, ok := x.Value.(*Attachment_PlainText); ok {
			return x.PlainText
		}
	}
	return ""
}

func (x *Attachment) GetExecutedShellCommand() *ExecutedShellCommand {
	if x != nil {
		if x, ok := x.Value.(*Attachment_ExecutedShellCommand); ok {
			return x.ExecutedShellCommand
		}
	}
	return nil
}

func (x *Attachment) GetRunningShellCommand() *RunningShellCommand {
	if x != nil {
		if x, ok := x.Value.(*Attachment_RunningShellCommand); ok {
			return x.RunningShellCommand
		}
	}
	return nil
}

func (x *Attachment) GetDriveObject() *DriveObject {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DriveObject); ok {
			return x.DriveObject
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in attachment.proto.
func (x *Attachment) GetDiffHunk() *DiffHunk {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DiffHunk); ok {
			return x.DiffHunk
		}
	}
	return nil
}

func (x *Attachment) GetDiffSet() *DiffSet {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DiffSet); ok {
			return x.DiffSet
		}
	}
	return nil
}

func (x *Attachment) GetDocumentContent() *DocumentContent {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DocumentContent); ok {
			return x.DocumentContent
		}
	}
	return nil
}

func (x *Attachment) GetFilePathReference() *FilePathReference {
	if x != nil {
		if x, ok := x.Value.(*Attachment_FilePathReference); ok {
			return x.FilePathReference
		}
	}
	return nil
}

type isAttachment_Value interface {
	isAttachment_Value()
}

type Attachment_PlainText struct {
	PlainText string `protobuf:"bytes,1,opt,name=plain_text,json=plainText,proto3,oneof"`
}

type Attachment_ExecutedShellCommand struct {
	ExecutedShellCommand *ExecutedShellCommand `protobuf:"bytes,2,opt,name=executed_shell_command,json=executedShellCommand,proto3,oneof"`
}

type Attachment_RunningShellCommand struct {
	RunningShellCommand *RunningShellCommand `protobuf:"bytes,3,opt,name=running_shell_command,json=runningShellCommand,proto3,oneof"`
}

type Attachment_DriveObject struct {
	DriveObject *DriveObject `protobuf:"bytes,4,opt,name=drive_object,json=driveObject,proto3,oneof"`
}

type Attachment_DiffHunk struct {
	// Deprecated: Represent a hunk as a DiffSet of size 1.
	//
	// Deprecated: Marked as deprecated in attachment.proto.
	DiffHunk *DiffHunk `protobuf:"bytes,5,opt,name=diff_hunk,json=diffHunk,proto3,oneof"`
}

type Attachment_DiffSet struct {
	DiffSet *DiffSet `protobuf:"bytes,6,opt,name=diff_set,json=diffSet,proto3,oneof"`
}

type Attachment_DocumentContent struct {
	DocumentContent *DocumentContent `protobuf:"bytes,7,opt,name=document_content,json=documentContent,proto3,oneof"`
}

type Attachment_FilePathReference struct {
	FilePathReference *FilePathReference `protobuf:"bytes,8,opt,name=file_path_reference,json=filePathReference,proto3,oneof"`
}

func (*Attachment_PlainText) isAttachment_Value() {}

func (*Attachment_ExecutedShellCommand) isAttachment_Value() {}

func (*Attachment_RunningShellCommand) isAttachment_Value() {}

func (*Attachment_DriveObject) isAttachment_Value() {}

func (*Attachment_DiffHunk) isAttachment_Value() {}

func (*Attachment_DiffSet) isAttachment_Value() {}

func (*Attachment_DocumentContent) isAttachment_Value() {}

func (*Attachment_FilePathReference) isAttachment_Value() {}

// Information about shell commands that the user has executed.
type ExecutedShellCommand struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Command    string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Output     string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode   int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	CommandId  string                 `protobuf:"bytes,4,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	StartedTs  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_ts,json=startedTs,proto3" json:"started_ts,omitempty"`
	FinishedTs *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_ts,json=finishedTs,proto3" json:"finished_ts,omitempty"`
	// `true` if the command was auto-attached.
	//
	// This is done by clients with `supports_auto_attached_commands` for user-executed commands in
	// the agent view.
	IsAutoAttached bool `protobuf:"varint,7,opt,name=is_auto_attached,json=isAutoAttached,proto3" json:"is_auto_attached,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutedShellCommand) Reset() {
	*x = ExecutedShellCommand{}
	mi := &file_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutedShellCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedShellCommand) ProtoMessage() {}

func (x *ExecutedShellCommand) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedShellCommand.ProtoReflect.Descriptor instead.
func (*ExecutedShellCommand) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutedShellCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecutedShellCommand) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecutedShellCommand) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutedShellCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecutedShellCommand) GetStartedTs() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedTs
	}
	return nil
}

func (x *ExecutedShellCommand) GetFinishedTs() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedTs
	}
	return nil
}

func (x *ExecutedShellCommand) GetIsAutoAttached() bool {
	if x != nil {
		return x.IsAutoAttached
	}
	return false
}

type RunningShellCommand struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Command       string                           `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Snapshot      *LongRunningShellCommandSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningShellCommand) Reset() {
	*x = RunningShellCommand{}
	mi := &file_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningShellCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningShellCommand) ProtoMessage() {}

func (x *RunningShellCommand) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningShellCommand.ProtoReflect.Descriptor instead.
func (*RunningShellCommand) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *RunningShellCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunningShellCommand) GetSnapshot() *LongRunningShellCommandSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// A snapshot of the terminal grid for a long-running command.
type LongRunningShellCommandSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw output grid contents.
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// The substring in 'output' used to represent the current cursor.
	//
	// This may be used by the server to find the cursor in `output` and change its formatting.
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// "ID" of the command execution to be included in tool calls to write to or read from the
	// snapshotted command.
	CommandId string `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Whether the terminal alternate screen buffer is active (e.g., pager, TUI application).
	// When true, the output is from the alternate screen buffer (like 'less', 'vim', 'top').
	// When false, the output is from the normal scrollback history.
	IsAltScreenActive bool `protobuf:"varint,4,opt,name=is_alt_screen_active,json=isAltScreenActive,proto3" json:"is_alt_screen_active,omitempty"`
	// Whether this snapshot was produced by preempting the agent's wait rather than by the command
	// completing or a scheduled timer expiring.
	//
	// Set to `true` when:
	//   - The agent requested `on_completion` but the client's 120s cap was hit before the command
	//     finished (the command is still running).
	//   - The user explicitly triggered an early snapshot (e.g. "Check now" affordance).
	//
	// When `true`, the server should inform the agent that the command is still running and that
	// it should not treat this as a completion signal.
	IsPreempted   bool `protobuf:"varint,5,opt,name=is_preempted,json=isPreempted,proto3" json:"is_preempted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongRunningShellCommandSnapshot) Reset() {
	*x = LongRunningShellCommandSnapshot{}
	mi := &file_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongRunningShellCommandSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongRunningShellCommandSnapshot) ProtoMessage() {}

func (x *LongRunningShellCommandSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongRunningShellCommandSnapshot.ProtoReflect.Descriptor instead.
func (*LongRunningShellCommandSnapshot) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *LongRunningShellCommandSnapshot) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *LongRunningShellCommandSnapshot) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *LongRunningShellCommandSnapshot) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *LongRunningShellCommandSnapshot) GetIsAltScreenActive() bool {
	if x != nil {
		return x.IsAltScreenActive
	}
	return false
}

func (x *LongRunningShellCommandSnapshot) GetIsPreempted() bool {
	if x != nil {
		return x.IsPreempted
	}
	return false
}

type DriveObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Types that are valid to be assigned to ObjectPayload:
	//
	//	*DriveObject_Workflow
	//	*DriveObject_Notebook
	//	*DriveObject_GenericStringObject
	ObjectPayload isDriveObject_ObjectPayload `protobuf_oneof:"object_payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveObject) Reset() {
	*x = DriveObject{}
	mi := &file_attachment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveObject) ProtoMessage() {}

func (x *DriveObject) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveObject.ProtoReflect.Descriptor instead.
func (*DriveObject) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *DriveObject) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DriveObject) GetObjectPayload() isDriveObject_ObjectPayload {
	if x != nil {
		return x.ObjectPayload
	}
	return nil
}

func (x *DriveObject) GetWorkflow() *Workflow {
	if x != nil {
		if x, ok := x.ObjectPayload.(*DriveObject_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *DriveObject) GetNotebook() *Notebook {
	if x != nil {
		if x, ok := x.ObjectPayload.(*DriveObject_Notebook); ok {
			return x.Notebook
		}
	}
	return nil
}

func (x *DriveObject) GetGenericStringObject() *GenericStringObject {
	if x != nil {
		if x, ok := x.ObjectPayload.(*DriveObject_GenericStringObject); ok {
			return x.GenericStringObject
		}
	}
	return nil
}

type isDriveObject_ObjectPayload interface {
	isDriveObject_ObjectPayload()
}

type DriveObject_Workflow struct {
	Workflow *Workflow `protobuf:"bytes,2,opt,name=workflow,proto3,oneof"`
}

type DriveObject_Notebook struct {
	Notebook *Notebook `protobuf:"bytes,3,opt,name=notebook,proto3,oneof"`
}

type DriveObject_GenericStringObject struct {
	GenericStringObject *GenericStringObject `protobuf:"bytes,4,opt,name=generic_string_object,json=genericStringObject,proto3,oneof"`
}

func (*DriveObject_Workflow) isDriveObject_ObjectPayload() {}

func (*DriveObject_Notebook) isDriveObject_ObjectPayload() {}

func (*DriveObject_GenericStringObject) isDriveObject_ObjectPayload() {}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_attachment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{5}
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Notebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notebook) Reset() {
	*x = Notebook{}
	mi := &file_attachment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notebook) ProtoMessage() {}

func (x *Notebook) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notebook.ProtoReflect.Descriptor instead.
func (*Notebook) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{6}
}

func (x *Notebook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notebook) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenericStringObject struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Payload string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Refers to the JSON type of the object such as "JsonEnvVarCollection" or "JsonAIFact"
	ObjectType    string `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericStringObject) Reset() {
	*x = GenericStringObject{}
	mi := &file_attachment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericStringObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericStringObject) ProtoMessage() {}

func (x *GenericStringObject) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericStringObject.ProtoReflect.Descriptor instead.
func (*GenericStringObject) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{7}
}

func (x *GenericStringObject) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GenericStringObject) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

// This has been deprecated.  Use DiffSets of size 1 instead.
type DiffHunk struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FilePath     string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineRange    *FileContentLineRange  `protobuf:"bytes,2,opt,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	DiffContent  string                 `protobuf:"bytes,3,opt,name=diff_content,json=diffContent,proto3" json:"diff_content,omitempty"`
	LinesAdded   uint32                 `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	LinesRemoved uint32                 `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	// Types that are valid to be assigned to Current:
	//
	//	*DiffHunk_CurrentBranchName
	//	*DiffHunk_CurrentHeadlessCommitSha
	Current isDiffHunk_Current `protobuf_oneof:"current"`
	// Types that are valid to be assigned to Base:
	//
	//	*DiffHunk_BaseBranchName
	//	*DiffHunk_BaseHeadlessCommitSha
	//	*DiffHunk_UncommittedChanges
	Base          isDiffHunk_Base `protobuf_oneof:"base"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffHunk) Reset() {
	*x = DiffHunk{}
	mi := &file_attachment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffHunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffHunk) ProtoMessage() {}

func (x *DiffHunk) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffHunk.ProtoReflect.Descriptor instead.
func (*DiffHunk) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{8}
}

func (x *DiffHunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DiffHunk) GetLineRange() *FileContentLineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

func (x *DiffHunk) GetDiffContent() string {
	if x != nil {
		return x.DiffContent
	}
	return ""
}

func (x *DiffHunk) GetLinesAdded() uint32 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *DiffHunk) GetLinesRemoved() uint32 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

func (x *DiffHunk) GetCurrent() isDiffHunk_Current {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *DiffHunk) GetCurrentBranchName() string {
	if x != nil {
		if x, ok := x.Current.(*DiffHunk_CurrentBranchName); ok {
			return x.CurrentBranchName
		}
	}
	return ""
}

func (x *DiffHunk) GetCurrentHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Current.(*DiffHunk_CurrentHeadlessCommitSha); ok {
			return x.CurrentHeadlessCommitSha
		}
	}
	return ""
}

func (x *DiffHunk) GetBase() isDiffHunk_Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DiffHunk) GetBaseBranchName() string {
	if x != nil {
		if x, ok := x.Base.(*DiffHunk_BaseBranchName); ok {
			return x.BaseBranchName
		}
	}
	return ""
}

func (x *DiffHunk) GetBaseHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Base.(*DiffHunk_BaseHeadlessCommitSha); ok {
			return x.BaseHeadlessCommitSha
		}
	}
	return ""
}

func (x *DiffHunk) GetUncommittedChanges() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Base.(*DiffHunk_UncommittedChanges); ok {
			return x.UncommittedChanges
		}
	}
	return nil
}

type isDiffHunk_Current interface {
	isDiffHunk_Current()
}

type DiffHunk_CurrentBranchName struct {
	CurrentBranchName string `protobuf:"bytes,6,opt,name=current_branch_name,json=currentBranchName,proto3,oneof"`
}

type DiffHunk_CurrentHeadlessCommitSha struct {
	CurrentHeadlessCommitSha string `protobuf:"bytes,7,opt,name=current_headless_commit_sha,json=currentHeadlessCommitSha,proto3,oneof"`
}

func (*DiffHunk_CurrentBranchName) isDiffHunk_Current() {}

func (*DiffHunk_CurrentHeadlessCommitSha) isDiffHunk_Current() {}

type isDiffHunk_Base interface {
	isDiffHunk_Base()
}

type DiffHunk_BaseBranchName struct {
	BaseBranchName string `protobuf:"bytes,8,opt,name=base_branch_name,json=baseBranchName,proto3,oneof"`
}

type DiffHunk_BaseHeadlessCommitSha struct {
	BaseHeadlessCommitSha string `protobuf:"bytes,9,opt,name=base_headless_commit_sha,json=baseHeadlessCommitSha,proto3,oneof"`
}

type DiffHunk_UncommittedChanges struct {
	UncommittedChanges *emptypb.Empty `protobuf:"bytes,10,opt,name=uncommitted_changes,json=uncommittedChanges,proto3,oneof"`
}

func (*DiffHunk_BaseBranchName) isDiffHunk_Base() {}

func (*DiffHunk_BaseHeadlessCommitSha) isDiffHunk_Base() {}

func (*DiffHunk_UncommittedChanges) isDiffHunk_Base() {}

// Reference to the current state (branch or commit)
type CurrentRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*CurrentRef_BranchName
	//	*CurrentRef_HeadlessCommitSha
	Ref           isCurrentRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentRef) Reset() {
	*x = CurrentRef{}
	mi := &file_attachment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentRef) ProtoMessage() {}

func (x *CurrentRef) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentRef.ProtoReflect.Descriptor instead.
func (*CurrentRef) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{9}
}

func (x *CurrentRef) GetRef() isCurrentRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *CurrentRef) GetBranchName() string {
	if x != nil {
		if x, ok := x.Ref.(*CurrentRef_BranchName); ok {
			return x.BranchName
		}
	}
	return ""
}

func (x *CurrentRef) GetHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Ref.(*CurrentRef_HeadlessCommitSha); ok {
			return x.HeadlessCommitSha
		}
	}
	return ""
}

type isCurrentRef_Ref interface {
	isCurrentRef_Ref()
}

type CurrentRef_BranchName struct {
	BranchName string `protobuf:"bytes,1,opt,name=branch_name,json=branchName,proto3,oneof"`
}

type CurrentRef_HeadlessCommitSha struct {
	HeadlessCommitSha string `protobuf:"bytes,2,opt,name=headless_commit_sha,json=headlessCommitSha,proto3,oneof"`
}

func (*CurrentRef_BranchName) isCurrentRef_Ref() {}

func (*CurrentRef_HeadlessCommitSha) isCurrentRef_Ref() {}

// Reference to the base state (branch, commit, or uncommitted changes)
type BaseRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*BaseRef_BranchName
	//	*BaseRef_HeadlessCommitSha
	//	*BaseRef_UncommittedChanges
	Ref           isBaseRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRef) Reset() {
	*x = BaseRef{}
	mi := &file_attachment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRef) ProtoMessage() {}

func (x *BaseRef) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRef.ProtoReflect.Descriptor instead.
func (*BaseRef) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{10}
}

func (x *BaseRef) GetRef() isBaseRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *BaseRef) GetBranchName() string {
	if x != nil {
		if x, ok := x.Ref.(*BaseRef_BranchName); ok {
			return x.BranchName
		}
	}
	return ""
}

func (x *BaseRef) GetHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Ref.(*BaseRef_HeadlessCommitSha); ok {
			return x.HeadlessCommitSha
		}
	}
	return ""
}

func (x *BaseRef) GetUncommittedChanges() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Ref.(*BaseRef_UncommittedChanges); ok {
			return x.UncommittedChanges
		}
	}
	return nil
}

type isBaseRef_Ref interface {
	isBaseRef_Ref()
}

type BaseRef_BranchName struct {
	BranchName string `protobuf:"bytes,1,opt,name=branch_name,json=branchName,proto3,oneof"`
}

type BaseRef_HeadlessCommitSha struct {
	HeadlessCommitSha string `protobuf:"bytes,2,opt,name=headless_commit_sha,json=headlessCommitSha,proto3,oneof"`
}

type BaseRef_UncommittedChanges struct {
	UncommittedChanges *emptypb.Empty `protobuf:"bytes,3,opt,name=uncommitted_changes,json=uncommittedChanges,proto3,oneof"`
}

func (*BaseRef_BranchName) isBaseRef_Ref() {}

func (*BaseRef_HeadlessCommitSha) isBaseRef_Ref() {}

func (*BaseRef_UncommittedChanges) isBaseRef_Ref() {}

type DiffSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hunks         []*DiffSet_DiffHunk    `protobuf:"bytes,1,rep,name=hunks,proto3" json:"hunks,omitempty"`
	CurrRef       *CurrentRef            `protobuf:"bytes,2,opt,name=curr_ref,json=currRef,proto3" json:"curr_ref,omitempty"`
	BaseRef       *BaseRef               `protobuf:"bytes,3,opt,name=base_ref,json=baseRef,proto3" json:"base_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffSet) Reset() {
	*x = DiffSet{}
	mi := &file_attachment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffSet) ProtoMessage() {}

func (x *DiffSet) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffSet.ProtoReflect.Descriptor instead.
func (*DiffSet) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{11}
}

func (x *DiffSet) GetHunks() []*DiffSet_DiffHunk {
	if x != nil {
		return x.Hunks
	}
	return nil
}

func (x *DiffSet) GetCurrRef() *CurrentRef {
	if x != nil {
		return x.CurrRef
	}
	return nil
}

func (x *DiffSet) GetBaseRef() *BaseRef {
	if x != nil {
		return x.BaseRef
	}
	return nil
}

// Reference to a file on the filesystem (e.g., downloaded attachments on VM)
type FilePathReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePathReference) Reset() {
	*x = FilePathReference{}
	mi := &file_attachment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePathReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePathReference) ProtoMessage() {}

func (x *FilePathReference) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePathReference.ProtoReflect.Descriptor instead.
func (*FilePathReference) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{12}
}

func (x *FilePathReference) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type DiffSet_DiffHunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineRange     *FileContentLineRange  `protobuf:"bytes,2,opt,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	DiffContent   string                 `protobuf:"bytes,3,opt,name=diff_content,json=diffContent,proto3" json:"diff_content,omitempty"`
	LinesAdded    uint32                 `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	LinesRemoved  uint32                 `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffSet_DiffHunk) Reset() {
	*x = DiffSet_DiffHunk{}
	mi := &file_attachment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffSet_DiffHunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffSet_DiffHunk) ProtoMessage() {}

func (x *DiffSet_DiffHunk) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffSet_DiffHunk.ProtoReflect.Descriptor instead.
func (*DiffSet_DiffHunk) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{11, 0}
}

func (x *DiffSet_DiffHunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DiffSet_DiffHunk) GetLineRange() *FileContentLineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

func (x *DiffSet_DiffHunk) GetDiffContent() string {
	if x != nil {
		return x.DiffContent
	}
	return ""
}

func (x *DiffSet_DiffHunk) GetLinesAdded() uint32 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *DiffSet_DiffHunk) GetLinesRemoved() uint32 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

var File_attachment_proto protoreflect.FileDescriptor

const file_attachment_proto_rawDesc = "" +
	"\n" +
	"\x10attachment.proto\x12\x13warp.multi_agent.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16document_content.proto\x1a\roptions.proto\x1a\x12file_content.proto\"\xf0\x04\n" +
	"\n" +
	"Attachment\x12%\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01H\x00R\tplainText\x12a\n" +
	"\x16executed_shell_command\x18\x02 \x01(\v2).warp.multi_agent.v1.ExecutedShellCommandH\x00R\x14executedShellCommand\x12^\n" +
	"\x15running_shell_command\x18\x03 \x01(\v2(.warp.multi_agent.v1.RunningShellCommandH\x00R\x13runningShellCommand\x12E\n" +
	"\fdrive_object\x18\x04 \x01(\v2 .warp.multi_agent.v1.DriveObjectH\x00R\vdriveObject\x12@\n" +
	"\tdiff_hunk\x18\x05 \x01(\v2\x1d.warp.multi_agent.v1.DiffHunkB\x02\x18\x01H\x00R\bdiffHunk\x129\n" +
	"\bdiff_set\x18\x06 \x01(\v2\x1c.warp.multi_agent.v1.DiffSetH\x00R\adiffSet\x12Q\n" +
	"\x10document_content\x18\a \x01(\v2$.warp.multi_agent.v1.DocumentContentH\x00R\x0fdocumentContent\x12X\n" +
	"\x13file_path_reference\x18\b \x01(\v2&.warp.multi_agent.v1.FilePathReferenceH\x00R\x11filePathReferenceB\a\n" +
	"\x05value\"\xb2\x02\n" +
	"\x14ExecutedShellCommand\x12\x1e\n" +
	"\acommand\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\acommand\x12\x1c\n" +
	"\x06output\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06output\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"command_id\x18\x04 \x01(\tR\tcommandId\x129\n" +
	"\n" +
	"started_ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedTs\x12;\n" +
	"\vfinished_ts\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedTs\x12(\n" +
	"\x10is_auto_attached\x18\a \x01(\bR\x0eisAutoAttached\"\x87\x01\n" +
	"\x13RunningShellCommand\x12\x1e\n" +
	"\acommand\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\acommand\x12P\n" +
	"\bsnapshot\x18\x02 \x01(\v24.warp.multi_agent.v1.LongRunningShellCommandSnapshotR\bsnapshot\"\xca\x01\n" +
	"\x1fLongRunningShellCommandSnapshot\x12\x1c\n" +
	"\x06output\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x06output\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12/\n" +
	"\x14is_alt_screen_active\x18\x04 \x01(\bR\x11isAltScreenActive\x12!\n" +
	"\fis_preempted\x18\x05 \x01(\bR\visPreempted\"\x91\x02\n" +
	"\vDriveObject\x12\x16\n" +
	"\x03uid\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x03uid\x12;\n" +
	"\bworkflow\x18\x02 \x01(\v2\x1d.warp.multi_agent.v1.WorkflowH\x00R\bworkflow\x12;\n" +
	"\bnotebook\x18\x03 \x01(\v2\x1d.warp.multi_agent.v1.NotebookH\x00R\bnotebook\x12^\n" +
	"\x15generic_string_object\x18\x04 \x01(\v2(.warp.multi_agent.v1.GenericStringObjectH\x00R\x13genericStringObjectB\x10\n" +
	"\x0eobject_payload\"l\n" +
	"\bWorkflow\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x04name\x12&\n" +
	"\vdescription\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\vdescription\x12\x1e\n" +
	"\acommand\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\acommand\"F\n" +
	"\bNotebook\x12\x1a\n" +
	"\x05title\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x05title\x12\x1e\n" +
	"\acontent\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\acontent\"V\n" +
	"\x13GenericStringObject\x12\x1e\n" +
	"\apayload\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\apayload\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\tR\n" +
	"objectType\"\xaa\x04\n" +
	"\bDiffHunk\x12!\n" +
	"\tfile_path\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\bfilePath\x12H\n" +
	"\n" +
	"line_range\x18\x02 \x01(\v2).warp.multi_agent.v1.FileContentLineRangeR\tlineRange\x12'\n" +
	"\fdiff_content\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\vdiffContent\x12\x1f\n" +
	"\vlines_added\x18\x04 \x01(\rR\n" +
	"linesAdded\x12#\n" +
	"\rlines_removed\x18\x05 \x01(\rR\flinesRemoved\x126\n" +
	"\x13current_branch_name\x18\x06 \x01(\tB\x04\x80\xb5\x18\x01H\x00R\x11currentBranchName\x12?\n" +
	"\x1bcurrent_headless_commit_sha\x18\a \x01(\tH\x00R\x18currentHeadlessCommitSha\x120\n" +
	"\x10base_branch_name\x18\b \x01(\tB\x04\x80\xb5\x18\x01H\x01R\x0ebaseBranchName\x129\n" +
	"\x18base_headless_commit_sha\x18\t \x01(\tH\x01R\x15baseHeadlessCommitSha\x12I\n" +
	"\x13uncommitted_changes\x18\n" +
	" \x01(\v2\x16.google.protobuf.EmptyH\x01R\x12uncommittedChangesB\t\n" +
	"\acurrentB\x06\n" +
	"\x04base\"n\n" +
	"\n" +
	"CurrentRef\x12'\n" +
	"\vbranch_name\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01H\x00R\n" +
	"branchName\x120\n" +
	"\x13headless_commit_sha\x18\x02 \x01(\tH\x00R\x11headlessCommitShaB\x05\n" +
	"\x03ref\"\xb6\x01\n" +
	"\aBaseRef\x12'\n" +
	"\vbranch_name\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01H\x00R\n" +
	"branchName\x120\n" +
	"\x13headless_commit_sha\x18\x02 \x01(\tH\x00R\x11headlessCommitSha\x12I\n" +
	"\x13uncommitted_changes\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x12uncommittedChangesB\x05\n" +
	"\x03ref\"\xa4\x03\n" +
	"\aDiffSet\x12;\n" +
	"\x05hunks\x18\x01 \x03(\v2%.warp.multi_agent.v1.DiffSet.DiffHunkR\x05hunks\x12:\n" +
	"\bcurr_ref\x18\x02 \x01(\v2\x1f.warp.multi_agent.v1.CurrentRefR\acurrRef\x127\n" +
	"\bbase_ref\x18\x03 \x01(\v2\x1c.warp.multi_agent.v1.BaseRefR\abaseRef\x1a\xe6\x01\n" +
	"\bDiffHunk\x12!\n" +
	"\tfile_path\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\bfilePath\x12H\n" +
	"\n" +
	"line_range\x18\x02 \x01(\v2).warp.multi_agent.v1.FileContentLineRangeR\tlineRange\x12'\n" +
	"\fdiff_content\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\vdiffContent\x12\x1f\n" +
	"\vlines_added\x18\x04 \x01(\rR\n" +
	"linesAdded\x12#\n" +
	"\rlines_removed\x18\x05 \x01(\rR\flinesRemoved\"6\n" +
	"\x11FilePathReference\x12!\n" +
	"\tfile_path\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\bfilePathb\x06proto3"

var (
	file_attachment_proto_rawDescOnce sync.Once
	file_attachment_proto_rawDescData []byte
)

func file_attachment_proto_rawDescGZIP() []byte {
	file_attachment_proto_rawDescOnce.Do(func() {
		file_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)))
	})
	return file_attachment_proto_rawDescData
}

var file_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_attachment_proto_goTypes = []any{
	(*Attachment)(nil),                      // 0: warp.multi_agent.v1.Attachment
	(*ExecutedShellCommand)(nil),            // 1: warp.multi_agent.v1.ExecutedShellCommand
	(*RunningShellCommand)(nil),             // 2: warp.multi_agent.v1.RunningShellCommand
	(*LongRunningShellCommandSnapshot)(nil), // 3: warp.multi_agent.v1.LongRunningShellCommandSnapshot
	(*DriveObject)(nil),                     // 4: warp.multi_agent.v1.DriveObject
	(*Workflow)(nil),                        // 5: warp.multi_agent.v1.Workflow
	(*Notebook)(nil),                        // 6: warp.multi_agent.v1.Notebook
	(*GenericStringObject)(nil),             // 7: warp.multi_agent.v1.GenericStringObject
	(*DiffHunk)(nil),                        // 8: warp.multi_agent.v1.DiffHunk
	(*CurrentRef)(nil),                      // 9: warp.multi_agent.v1.CurrentRef
	(*BaseRef)(nil),                         // 10: warp.multi_agent.v1.BaseRef
	(*DiffSet)(nil),                         // 11: warp.multi_agent.v1.DiffSet
	(*FilePathReference)(nil),               // 12: warp.multi_agent.v1.FilePathReference
	(*DiffSet_DiffHunk)(nil),                // 13: warp.multi_agent.v1.DiffSet.DiffHunk
	(*DocumentContent)(nil),                 // 14: warp.multi_agent.v1.DocumentContent
	(*timestamppb.Timestamp)(nil),           // 15: google.protobuf.Timestamp
	(*FileContentLineRange)(nil),            // 16: warp.multi_agent.v1.FileContentLineRange
	(*emptypb.Empty)(nil),                   // 17: google.protobuf.Empty
}
var file_attachment_proto_depIdxs = []int32{
	1,  // 0: warp.multi_agent.v1.Attachment.executed_shell_command:type_name -> warp.multi_agent.v1.ExecutedShellCommand
	2,  // 1: warp.multi_agent.v1.Attachment.running_shell_command:type_name -> warp.multi_agent.v1.RunningShellCommand
	4,  // 2: warp.multi_agent.v1.Attachment.drive_object:type_name -> warp.multi_agent.v1.DriveObject
	8,  // 3: warp.multi_agent.v1.Attachment.diff_hunk:type_name -> warp.multi_agent.v1.DiffHunk
	11, // 4: warp.multi_agent.v1.Attachment.diff_set:type_name -> warp.multi_agent.v1.DiffSet
	14, // 5: warp.multi_agent.v1.Attachment.document_content:type_name -> warp.multi_agent.v1.DocumentContent
	12, // 6: warp.multi_agent.v1.Attachment.file_path_reference:type_name -> warp.multi_agent.v1.FilePathReference
	15, // 7: warp.multi_agent.v1.ExecutedShellCommand.started_ts:type_name -> google.protobuf.Timestamp
	15, // 8: warp.multi_agent.v1.ExecutedShellCommand.finished_ts:type_name -> google.protobuf.Timestamp
	3,  // 9: warp.multi_agent.v1.RunningShellCommand.snapshot:type_name -> warp.multi_agent.v1.LongRunningShellCommandSnapshot
	5,  // 10: warp.multi_agent.v1.DriveObject.workflow:type_name -> warp.multi_agent.v1.Workflow
	6,  // 11: warp.multi_agent.v1.DriveObject.notebook:type_name -> warp.multi_agent.v1.Notebook
	7,  // 12: warp.multi_agent.v1.DriveObject.generic_string_object:type_name -> warp.multi_agent.v1.GenericStringObject
	16, // 13: warp.multi_agent.v1.DiffHunk.line_range:type_name -> warp.multi_agent.v1.FileContentLineRange
	17, // 14: warp.multi_agent.v1.DiffHunk.uncommitted_changes:type_name -> google.protobuf.Empty
	17, // 15: warp.multi_agent.v1.BaseRef.uncommitted_changes:type_name -> google.protobuf.Empty
	13, // 16: warp.multi_agent.v1.DiffSet.hunks:type_name -> warp.multi_agent.v1.DiffSet.DiffHunk
	9,  // 17: warp.multi_agent.v1.DiffSet.curr_ref:type_name -> warp.multi_agent.v1.CurrentRef
	10, // 18: warp.multi_agent.v1.DiffSet.base_ref:type_name -> warp.multi_agent.v1.BaseRef
	16, // 19: warp.multi_agent.v1.DiffSet.DiffHunk.line_range:type_name -> warp.multi_agent.v1.FileContentLineRange
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_attachment_proto_init() }
func file_attachment_proto_init() {
	if File_attachment_proto != nil {
		return
	}
	file_document_content_proto_init()
	file_options_proto_init()
	file_file_content_proto_init()
	file_attachment_proto_msgTypes[0].OneofWrappers = []any{
		(*Attachment_PlainText)(nil),
		(*Attachment_ExecutedShellCommand)(nil),
		(*Attachment_RunningShellCommand)(nil),
		(*Attachment_DriveObject)(nil),
		(*Attachment_DiffHunk)(nil),
		(*Attachment_DiffSet)(nil),
		(*Attachment_DocumentContent)(nil),
		(*Attachment_FilePathReference)(nil),
	}
	file_attachment_proto_msgTypes[4].OneofWrappers = []any{
		(*DriveObject_Workflow)(nil),
		(*DriveObject_Notebook)(nil),
		(*DriveObject_GenericStringObject)(nil),
	}
	file_attachment_proto_msgTypes[8].OneofWrappers = []any{
		(*DiffHunk_CurrentBranchName)(nil),
		(*DiffHunk_CurrentHeadlessCommitSha)(nil),
		(*DiffHunk_BaseBranchName)(nil),
		(*DiffHunk_BaseHeadlessCommitSha)(nil),
		(*DiffHunk_UncommittedChanges)(nil),
	}
	file_attachment_proto_msgTypes[9].OneofWrappers = []any{
		(*CurrentRef_BranchName)(nil),
		(*CurrentRef_HeadlessCommitSha)(nil),
	}
	file_attachment_proto_msgTypes[10].OneofWrappers = []any{
		(*BaseRef_BranchName)(nil),
		(*BaseRef_HeadlessCommitSha)(nil),
		(*BaseRef_UncommittedChanges)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attachment_proto_goTypes,
		DependencyIndexes: file_attachment_proto_depIdxs,
		MessageInfos:      file_attachment_proto_msgTypes,
	}.Build()
	File_attachment_proto = out.File
	file_attachment_proto_goTypes = nil
	file_attachment_proto_depIdxs = nil
}
