// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: citations.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentType represents the various types of documents that can be cited.
type DocumentType int32

const (
	DocumentType_WARP_DRIVE_WORKFLOW DocumentType = 0
	DocumentType_WARP_DRIVE_NOTEBOOK DocumentType = 1
	DocumentType_WARP_DRIVE_ENV_VAR  DocumentType = 2
	DocumentType_RULE                DocumentType = 3
	DocumentType_WARP_DOCUMENTATION  DocumentType = 4
	DocumentType_WEB_PAGE            DocumentType = 5
	DocumentType_UNKNOWN             DocumentType = 6
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "WARP_DRIVE_WORKFLOW",
		1: "WARP_DRIVE_NOTEBOOK",
		2: "WARP_DRIVE_ENV_VAR",
		3: "RULE",
		4: "WARP_DOCUMENTATION",
		5: "WEB_PAGE",
		6: "UNKNOWN",
	}
	DocumentType_value = map[string]int32{
		"WARP_DRIVE_WORKFLOW": 0,
		"WARP_DRIVE_NOTEBOOK": 1,
		"WARP_DRIVE_ENV_VAR":  2,
		"RULE":                3,
		"WARP_DOCUMENTATION":  4,
		"WEB_PAGE":            5,
		"UNKNOWN":             6,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_citations_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_citations_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_citations_proto_rawDescGZIP(), []int{0}
}

// Citation represents a reference to a specific document or resource that was used by the LLM in generating
// the response. Citations can be included both on the message level or on individual tool calls
// It includes both the unique identifier of the document and its type classification.
type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentType  DocumentType           `protobuf:"varint,2,opt,name=document_type,json=documentType,proto3,enum=warp.multi_agent.v1.DocumentType" json:"document_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_citations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_citations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_citations_proto_rawDescGZIP(), []int{0}
}

func (x *Citation) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Citation) GetDocumentType() DocumentType {
	if x != nil {
		return x.DocumentType
	}
	return DocumentType_WARP_DRIVE_WORKFLOW
}

var File_citations_proto protoreflect.FileDescriptor

const file_citations_proto_rawDesc = "" +
	"\n" +
	"\x0fcitations.proto\x12\x13warp.multi_agent.v1\"s\n" +
	"\bCitation\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12F\n" +
	"\rdocument_type\x18\x02 \x01(\x0e2!.warp.multi_agent.v1.DocumentTypeR\fdocumentType*\x95\x01\n" +
	"\fDocumentType\x12\x17\n" +
	"\x13WARP_DRIVE_WORKFLOW\x10\x00\x12\x17\n" +
	"\x13WARP_DRIVE_NOTEBOOK\x10\x01\x12\x16\n" +
	"\x12WARP_DRIVE_ENV_VAR\x10\x02\x12\b\n" +
	"\x04RULE\x10\x03\x12\x16\n" +
	"\x12WARP_DOCUMENTATION\x10\x04\x12\f\n" +
	"\bWEB_PAGE\x10\x05\x12\v\n" +
	"\aUNKNOWN\x10\x06b\x06proto3"

var (
	file_citations_proto_rawDescOnce sync.Once
	file_citations_proto_rawDescData []byte
)

func file_citations_proto_rawDescGZIP() []byte {
	file_citations_proto_rawDescOnce.Do(func() {
		file_citations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_citations_proto_rawDesc), len(file_citations_proto_rawDesc)))
	})
	return file_citations_proto_rawDescData
}

var file_citations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_citations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_citations_proto_goTypes = []any{
	(DocumentType)(0), // 0: warp.multi_agent.v1.DocumentType
	(*Citation)(nil),  // 1: warp.multi_agent.v1.Citation
}
var file_citations_proto_depIdxs = []int32{
	0, // 0: warp.multi_agent.v1.Citation.document_type:type_name -> warp.multi_agent.v1.DocumentType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_citations_proto_init() }
func file_citations_proto_init() {
	if File_citations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_citations_proto_rawDesc), len(file_citations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_citations_proto_goTypes,
		DependencyIndexes: file_citations_proto_depIdxs,
		EnumInfos:         file_citations_proto_enumTypes,
		MessageInfos:      file_citations_proto_msgTypes,
	}.Build()
	File_citations_proto = out.File
	file_citations_proto_goTypes = nil
	file_citations_proto_depIdxs = nil
}
