// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: document_content.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A representation of text content within a document.
type DocumentContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LineRange     *FileContentLineRange  `protobuf:"bytes,3,opt,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentContent) Reset() {
	*x = DocumentContent{}
	mi := &file_document_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentContent) ProtoMessage() {}

func (x *DocumentContent) ProtoReflect() protoreflect.Message {
	mi := &file_document_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentContent.ProtoReflect.Descriptor instead.
func (*DocumentContent) Descriptor() ([]byte, []int) {
	return file_document_content_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentContent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentContent) GetLineRange() *FileContentLineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

var File_document_content_proto protoreflect.FileDescriptor

const file_document_content_proto_rawDesc = "" +
	"\n" +
	"\x16document_content.proto\x12\x13warp.multi_agent.v1\x1a\roptions.proto\x1a\x12file_content.proto\"\x9c\x01\n" +
	"\x0fDocumentContent\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1e\n" +
	"\acontent\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\acontent\x12H\n" +
	"\n" +
	"line_range\x18\x03 \x01(\v2).warp.multi_agent.v1.FileContentLineRangeR\tlineRangeb\x06proto3"

var (
	file_document_content_proto_rawDescOnce sync.Once
	file_document_content_proto_rawDescData []byte
)

func file_document_content_proto_rawDescGZIP() []byte {
	file_document_content_proto_rawDescOnce.Do(func() {
		file_document_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_content_proto_rawDesc), len(file_document_content_proto_rawDesc)))
	})
	return file_document_content_proto_rawDescData
}

var file_document_content_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_document_content_proto_goTypes = []any{
	(*DocumentContent)(nil),      // 0: warp.multi_agent.v1.DocumentContent
	(*FileContentLineRange)(nil), // 1: warp.multi_agent.v1.FileContentLineRange
}
var file_document_content_proto_depIdxs = []int32{
	1, // 0: warp.multi_agent.v1.DocumentContent.line_range:type_name -> warp.multi_agent.v1.FileContentLineRange
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_document_content_proto_init() }
func file_document_content_proto_init() {
	if File_document_content_proto != nil {
		return
	}
	file_options_proto_init()
	file_file_content_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_content_proto_rawDesc), len(file_document_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_document_content_proto_goTypes,
		DependencyIndexes: file_document_content_proto_depIdxs,
		MessageInfos:      file_document_content_proto_msgTypes,
	}.Build()
	File_document_content_proto = out.File
	file_document_content_proto_goTypes = nil
	file_document_content_proto_depIdxs = nil
}
