// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: file_content.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A range of lines [start, end] that situate content in a file, 1-indexed.
type FileContentLineRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContentLineRange) Reset() {
	*x = FileContentLineRange{}
	mi := &file_file_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContentLineRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContentLineRange) ProtoMessage() {}

func (x *FileContentLineRange) ProtoReflect() protoreflect.Message {
	mi := &file_file_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContentLineRange.ProtoReflect.Descriptor instead.
func (*FileContentLineRange) Descriptor() ([]byte, []int) {
	return file_file_content_proto_rawDescGZIP(), []int{0}
}

func (x *FileContentLineRange) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FileContentLineRange) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// A representation of text content within a file.
type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LineRange     *FileContentLineRange  `protobuf:"bytes,3,opt,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_file_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_file_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_file_content_proto_rawDescGZIP(), []int{1}
}

func (x *FileContent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileContent) GetLineRange() *FileContentLineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

// A representation of binary content within a file.
type BinaryFileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryFileContent) Reset() {
	*x = BinaryFileContent{}
	mi := &file_file_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryFileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryFileContent) ProtoMessage() {}

func (x *BinaryFileContent) ProtoReflect() protoreflect.Message {
	mi := &file_file_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryFileContent.ProtoReflect.Descriptor instead.
func (*BinaryFileContent) Descriptor() ([]byte, []int) {
	return file_file_content_proto_rawDescGZIP(), []int{2}
}

func (x *BinaryFileContent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BinaryFileContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A representation of binary or text content within a file.
type AnyFileContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*AnyFileContent_BinaryContent
	//	*AnyFileContent_TextContent
	Content       isAnyFileContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyFileContent) Reset() {
	*x = AnyFileContent{}
	mi := &file_file_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyFileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyFileContent) ProtoMessage() {}

func (x *AnyFileContent) ProtoReflect() protoreflect.Message {
	mi := &file_file_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyFileContent.ProtoReflect.Descriptor instead.
func (*AnyFileContent) Descriptor() ([]byte, []int) {
	return file_file_content_proto_rawDescGZIP(), []int{3}
}

func (x *AnyFileContent) GetContent() isAnyFileContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AnyFileContent) GetBinaryContent() *BinaryFileContent {
	if x != nil {
		if x, ok := x.Content.(*AnyFileContent_BinaryContent); ok {
			return x.BinaryContent
		}
	}
	return nil
}

func (x *AnyFileContent) GetTextContent() *FileContent {
	if x != nil {
		if x, ok := x.Content.(*AnyFileContent_TextContent); ok {
			return x.TextContent
		}
	}
	return nil
}

type isAnyFileContent_Content interface {
	isAnyFileContent_Content()
}

type AnyFileContent_BinaryContent struct {
	BinaryContent *BinaryFileContent `protobuf:"bytes,1,opt,name=binary_content,json=binaryContent,proto3,oneof"`
}

type AnyFileContent_TextContent struct {
	TextContent *FileContent `protobuf:"bytes,2,opt,name=text_content,json=textContent,proto3,oneof"`
}

func (*AnyFileContent_BinaryContent) isAnyFileContent_Content() {}

func (*AnyFileContent_TextContent) isAnyFileContent_Content() {}

var File_file_content_proto protoreflect.FileDescriptor

const file_file_content_proto_rawDesc = "" +
	"\n" +
	"\x12file_content.proto\x12\x13warp.multi_agent.v1\x1a\roptions.proto\">\n" +
	"\x14FileContentLineRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"\x9a\x01\n" +
	"\vFileContent\x12!\n" +
	"\tfile_path\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\bfilePath\x12\x1e\n" +
	"\acontent\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\acontent\x12H\n" +
	"\n" +
	"line_range\x18\x03 \x01(\v2).warp.multi_agent.v1.FileContentLineRangeR\tlineRange\"J\n" +
	"\x11BinaryFileContent\x12!\n" +
	"\tfile_path\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\bfilePath\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xb3\x01\n" +
	"\x0eAnyFileContent\x12O\n" +
	"\x0ebinary_content\x18\x01 \x01(\v2&.warp.multi_agent.v1.BinaryFileContentH\x00R\rbinaryContent\x12E\n" +
	"\ftext_content\x18\x02 \x01(\v2 .warp.multi_agent.v1.FileContentH\x00R\vtextContentB\t\n" +
	"\acontentb\x06proto3"

var (
	file_file_content_proto_rawDescOnce sync.Once
	file_file_content_proto_rawDescData []byte
)

func file_file_content_proto_rawDescGZIP() []byte {
	file_file_content_proto_rawDescOnce.Do(func() {
		file_file_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_content_proto_rawDesc), len(file_file_content_proto_rawDesc)))
	})
	return file_file_content_proto_rawDescData
}

var file_file_content_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_content_proto_goTypes = []any{
	(*FileContentLineRange)(nil), // 0: warp.multi_agent.v1.FileContentLineRange
	(*FileContent)(nil),          // 1: warp.multi_agent.v1.FileContent
	(*BinaryFileContent)(nil),    // 2: warp.multi_agent.v1.BinaryFileContent
	(*AnyFileContent)(nil),       // 3: warp.multi_agent.v1.AnyFileContent
}
var file_file_content_proto_depIdxs = []int32{
	0, // 0: warp.multi_agent.v1.FileContent.line_range:type_name -> warp.multi_agent.v1.FileContentLineRange
	2, // 1: warp.multi_agent.v1.AnyFileContent.binary_content:type_name -> warp.multi_agent.v1.BinaryFileContent
	1, // 2: warp.multi_agent.v1.AnyFileContent.text_content:type_name -> warp.multi_agent.v1.FileContent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_file_content_proto_init() }
func file_file_content_proto_init() {
	if File_file_content_proto != nil {
		return
	}
	file_options_proto_init()
	file_file_content_proto_msgTypes[3].OneofWrappers = []any{
		(*AnyFileContent_BinaryContent)(nil),
		(*AnyFileContent_TextContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_content_proto_rawDesc), len(file_file_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_content_proto_goTypes,
		DependencyIndexes: file_file_content_proto_depIdxs,
		MessageInfos:      file_file_content_proto_msgTypes,
	}.Build()
	File_file_content_proto = out.File
	file_file_content_proto_goTypes = nil
	file_file_content_proto_depIdxs = nil
}
