// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: input_context.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Context that may be relevant to the input in a request.
type InputContext struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Directory       *InputContext_Directory       `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	OperatingSystem *InputContext_OperatingSystem `protobuf:"bytes,2,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Shell           *InputContext_Shell           `protobuf:"bytes,3,opt,name=shell,proto3" json:"shell,omitempty"`
	CurrentTime     *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	Codebases       []*InputContext_Codebase      `protobuf:"bytes,8,rep,name=codebases,proto3" json:"codebases,omitempty"`
	ProjectRules    []*InputContext_ProjectRules  `protobuf:"bytes,10,rep,name=project_rules,json=projectRules,proto3" json:"project_rules,omitempty"`
	Git             *InputContext_Git             `protobuf:"bytes,11,opt,name=git,proto3" json:"git,omitempty"`
	// Sent on each request when scoped skills change
	UpdatedSkillsContext *InputContext_SkillsContext `protobuf:"bytes,12,opt,name=updated_skills_context,json=updatedSkillsContext,proto3" json:"updated_skills_context,omitempty"`
	// Sent on each request when LSP servers change
	UpdatedLspServersContext *InputContext_LspServersContext `protobuf:"bytes,13,opt,name=updated_lsp_servers_context,json=updatedLspServersContext,proto3" json:"updated_lsp_servers_context,omitempty"`
	// TODO: these fields should be _attachments_, not part of the input context.
	//
	// Deprecated: Marked as deprecated in input_context.proto.
	ExecutedShellCommands []*ExecutedShellCommand      `protobuf:"bytes,5,rep,name=executed_shell_commands,json=executedShellCommands,proto3" json:"executed_shell_commands,omitempty"`
	SelectedText          []*InputContext_SelectedText `protobuf:"bytes,6,rep,name=selected_text,json=selectedText,proto3" json:"selected_text,omitempty"`
	Images                []*InputContext_Image        `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Files                 []*InputContext_File         `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"` // END TODO
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InputContext) Reset() {
	*x = InputContext{}
	mi := &file_input_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext) ProtoMessage() {}

func (x *InputContext) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext.ProtoReflect.Descriptor instead.
func (*InputContext) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0}
}

func (x *InputContext) GetDirectory() *InputContext_Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

func (x *InputContext) GetOperatingSystem() *InputContext_OperatingSystem {
	if x != nil {
		return x.OperatingSystem
	}
	return nil
}

func (x *InputContext) GetShell() *InputContext_Shell {
	if x != nil {
		return x.Shell
	}
	return nil
}

func (x *InputContext) GetCurrentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentTime
	}
	return nil
}

func (x *InputContext) GetCodebases() []*InputContext_Codebase {
	if x != nil {
		return x.Codebases
	}
	return nil
}

func (x *InputContext) GetProjectRules() []*InputContext_ProjectRules {
	if x != nil {
		return x.ProjectRules
	}
	return nil
}

func (x *InputContext) GetGit() *InputContext_Git {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *InputContext) GetUpdatedSkillsContext() *InputContext_SkillsContext {
	if x != nil {
		return x.UpdatedSkillsContext
	}
	return nil
}

func (x *InputContext) GetUpdatedLspServersContext() *InputContext_LspServersContext {
	if x != nil {
		return x.UpdatedLspServersContext
	}
	return nil
}

// Deprecated: Marked as deprecated in input_context.proto.
func (x *InputContext) GetExecutedShellCommands() []*ExecutedShellCommand {
	if x != nil {
		return x.ExecutedShellCommands
	}
	return nil
}

func (x *InputContext) GetSelectedText() []*InputContext_SelectedText {
	if x != nil {
		return x.SelectedText
	}
	return nil
}

func (x *InputContext) GetImages() []*InputContext_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *InputContext) GetFiles() []*InputContext_File {
	if x != nil {
		return x.Files
	}
	return nil
}

type InputContext_SelectedText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_SelectedText) Reset() {
	*x = InputContext_SelectedText{}
	mi := &file_input_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_SelectedText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_SelectedText) ProtoMessage() {}

func (x *InputContext_SelectedText) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_SelectedText.ProtoReflect.Descriptor instead.
func (*InputContext_SelectedText) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InputContext_SelectedText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Information about the user's directories.
type InputContext_Directory struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Pwd                   string                 `protobuf:"bytes,1,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Home                  string                 `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	PwdFileSymbolsIndexed bool                   `protobuf:"varint,3,opt,name=pwd_file_symbols_indexed,json=pwdFileSymbolsIndexed,proto3" json:"pwd_file_symbols_indexed,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InputContext_Directory) Reset() {
	*x = InputContext_Directory{}
	mi := &file_input_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Directory) ProtoMessage() {}

func (x *InputContext_Directory) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Directory.ProtoReflect.Descriptor instead.
func (*InputContext_Directory) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 1}
}

func (x *InputContext_Directory) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *InputContext_Directory) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *InputContext_Directory) GetPwdFileSymbolsIndexed() bool {
	if x != nil {
		return x.PwdFileSymbolsIndexed
	}
	return false
}

// Information about the user's terminal shell.
type InputContext_Shell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Shell) Reset() {
	*x = InputContext_Shell{}
	mi := &file_input_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Shell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Shell) ProtoMessage() {}

func (x *InputContext_Shell) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Shell.ProtoReflect.Descriptor instead.
func (*InputContext_Shell) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 2}
}

func (x *InputContext_Shell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputContext_Shell) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Information about the user's operating system.
type InputContext_OperatingSystem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OS "category", e.g. "MacOS" or "Linux".
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// The OS distribution, which is typically only populated for Linux,
	// e.g. Fedora or Ubuntu.
	Distribution  string `protobuf:"bytes,2,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_OperatingSystem) Reset() {
	*x = InputContext_OperatingSystem{}
	mi := &file_input_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_OperatingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_OperatingSystem) ProtoMessage() {}

func (x *InputContext_OperatingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_OperatingSystem.ProtoReflect.Descriptor instead.
func (*InputContext_OperatingSystem) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 3}
}

func (x *InputContext_OperatingSystem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *InputContext_OperatingSystem) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

// Any attached images.
type InputContext_Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image payload.
	//
	// TODO: the client should NOT base64 encode the image data.
	// It should send up raw binary data and the server should
	// do what it needs to (e.g. b64 encode before sending to LLM).
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// MIME type of the image content (e.g., "image/jpeg", "image/png").
	MimeType      string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Image) Reset() {
	*x = InputContext_Image{}
	mi := &file_input_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Image) ProtoMessage() {}

func (x *InputContext_Image) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Image.ProtoReflect.Descriptor instead.
func (*InputContext_Image) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 4}
}

func (x *InputContext_Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InputContext_Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// Information about a codebase on the user's machine that we can search.
type InputContext_Codebase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the codebase.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The absolute path to the codebase on the user's machine.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Codebase) Reset() {
	*x = InputContext_Codebase{}
	mi := &file_input_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Codebase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Codebase) ProtoMessage() {}

func (x *InputContext_Codebase) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Codebase.ProtoReflect.Descriptor instead.
func (*InputContext_Codebase) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 5}
}

func (x *InputContext_Codebase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputContext_Codebase) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InputContext_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *FileContent           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_File) Reset() {
	*x = InputContext_File{}
	mi := &file_input_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_File) ProtoMessage() {}

func (x *InputContext_File) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_File.ProtoReflect.Descriptor instead.
func (*InputContext_File) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 6}
}

func (x *InputContext_File) GetContent() *FileContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type InputContext_ProjectRules struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RootPath string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	// Active rules that should be eagerly applied to the conversation.
	ActiveRuleFiles []*FileContent `protobuf:"bytes,2,rep,name=active_rule_files,json=activeRuleFiles,proto3" json:"active_rule_files,omitempty"`
	// Additional rules that are available to be retrieved.
	AdditionalRuleFilePaths []string `protobuf:"bytes,3,rep,name=additional_rule_file_paths,json=additionalRuleFilePaths,proto3" json:"additional_rule_file_paths,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InputContext_ProjectRules) Reset() {
	*x = InputContext_ProjectRules{}
	mi := &file_input_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_ProjectRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_ProjectRules) ProtoMessage() {}

func (x *InputContext_ProjectRules) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_ProjectRules.ProtoReflect.Descriptor instead.
func (*InputContext_ProjectRules) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 7}
}

func (x *InputContext_ProjectRules) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *InputContext_ProjectRules) GetActiveRuleFiles() []*FileContent {
	if x != nil {
		return x.ActiveRuleFiles
	}
	return nil
}

func (x *InputContext_ProjectRules) GetAdditionalRuleFilePaths() []string {
	if x != nil {
		return x.AdditionalRuleFilePaths
	}
	return nil
}

// Context about the repo in the user's working directory.
type InputContext_Git struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's current head (i.e. branch name or commit hash).
	Head string `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// The current branch name, populated only from `git symbolic-ref --short HEAD`.
	// Empty/absent when in detached HEAD state.
	Branch        string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Git) Reset() {
	*x = InputContext_Git{}
	mi := &file_input_context_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Git) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Git) ProtoMessage() {}

func (x *InputContext_Git) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Git.ProtoReflect.Descriptor instead.
func (*InputContext_Git) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 8}
}

func (x *InputContext_Git) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *InputContext_Git) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type InputContext_SkillsContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AvailableSkills []*SkillDescriptor     `protobuf:"bytes,1,rep,name=available_skills,json=availableSkills,proto3" json:"available_skills,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InputContext_SkillsContext) Reset() {
	*x = InputContext_SkillsContext{}
	mi := &file_input_context_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_SkillsContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_SkillsContext) ProtoMessage() {}

func (x *InputContext_SkillsContext) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_SkillsContext.ProtoReflect.Descriptor instead.
func (*InputContext_SkillsContext) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 9}
}

func (x *InputContext_SkillsContext) GetAvailableSkills() []*SkillDescriptor {
	if x != nil {
		return x.AvailableSkills
	}
	return nil
}

type InputContext_LspServersContext struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AvailableLspServers []*LspDescriptor       `protobuf:"bytes,1,rep,name=available_lsp_servers,json=availableLspServers,proto3" json:"available_lsp_servers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InputContext_LspServersContext) Reset() {
	*x = InputContext_LspServersContext{}
	mi := &file_input_context_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_LspServersContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_LspServersContext) ProtoMessage() {}

func (x *InputContext_LspServersContext) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_LspServersContext.ProtoReflect.Descriptor instead.
func (*InputContext_LspServersContext) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 10}
}

func (x *InputContext_LspServersContext) GetAvailableLspServers() []*LspDescriptor {
	if x != nil {
		return x.AvailableLspServers
	}
	return nil
}

var File_input_context_proto protoreflect.FileDescriptor

const file_input_context_proto_rawDesc = "" +
	"\n" +
	"\x13input_context.proto\x12\x13warp.multi_agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12file_content.proto\x1a\x10attachment.proto\x1a\roptions.proto\x1a\vskill.proto\x1a\tlsp.proto\"\xda\x0f\n" +
	"\fInputContext\x12I\n" +
	"\tdirectory\x18\x01 \x01(\v2+.warp.multi_agent.v1.InputContext.DirectoryR\tdirectory\x12\\\n" +
	"\x10operating_system\x18\x02 \x01(\v21.warp.multi_agent.v1.InputContext.OperatingSystemR\x0foperatingSystem\x12=\n" +
	"\x05shell\x18\x03 \x01(\v2'.warp.multi_agent.v1.InputContext.ShellR\x05shell\x12=\n" +
	"\fcurrent_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcurrentTime\x12H\n" +
	"\tcodebases\x18\b \x03(\v2*.warp.multi_agent.v1.InputContext.CodebaseR\tcodebases\x12S\n" +
	"\rproject_rules\x18\n" +
	" \x03(\v2..warp.multi_agent.v1.InputContext.ProjectRulesR\fprojectRules\x127\n" +
	"\x03git\x18\v \x01(\v2%.warp.multi_agent.v1.InputContext.GitR\x03git\x12e\n" +
	"\x16updated_skills_context\x18\f \x01(\v2/.warp.multi_agent.v1.InputContext.SkillsContextR\x14updatedSkillsContext\x12r\n" +
	"\x1bupdated_lsp_servers_context\x18\r \x01(\v23.warp.multi_agent.v1.InputContext.LspServersContextR\x18updatedLspServersContext\x12e\n" +
	"\x17executed_shell_commands\x18\x05 \x03(\v2).warp.multi_agent.v1.ExecutedShellCommandB\x02\x18\x01R\x15executedShellCommands\x12S\n" +
	"\rselected_text\x18\x06 \x03(\v2..warp.multi_agent.v1.InputContext.SelectedTextR\fselectedText\x12?\n" +
	"\x06images\x18\a \x03(\v2'.warp.multi_agent.v1.InputContext.ImageR\x06images\x12<\n" +
	"\x05files\x18\t \x03(\v2&.warp.multi_agent.v1.InputContext.FileR\x05files\x1a(\n" +
	"\fSelectedText\x12\x18\n" +
	"\x04text\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x04text\x1av\n" +
	"\tDirectory\x12\x16\n" +
	"\x03pwd\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x03pwd\x12\x18\n" +
	"\x04home\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x04home\x127\n" +
	"\x18pwd_file_symbols_indexed\x18\x03 \x01(\bR\x15pwdFileSymbolsIndexed\x1a5\n" +
	"\x05Shell\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x1aQ\n" +
	"\x0fOperatingSystem\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\"\n" +
	"\fdistribution\x18\x02 \x01(\tR\fdistribution\x1a>\n" +
	"\x05Image\x12\x18\n" +
	"\x04data\x18\x01 \x01(\fB\x04\x80\xb5\x18\x01R\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x1a>\n" +
	"\bCodebase\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x04name\x12\x18\n" +
	"\x04path\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x04path\x1aB\n" +
	"\x04File\x12:\n" +
	"\acontent\x18\x01 \x01(\v2 .warp.multi_agent.v1.FileContentR\acontent\x1a\xb6\x01\n" +
	"\fProjectRules\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12L\n" +
	"\x11active_rule_files\x18\x02 \x03(\v2 .warp.multi_agent.v1.FileContentR\x0factiveRuleFiles\x12;\n" +
	"\x1aadditional_rule_file_paths\x18\x03 \x03(\tR\x17additionalRuleFilePaths\x1a=\n" +
	"\x03Git\x12\x18\n" +
	"\x04head\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x04head\x12\x1c\n" +
	"\x06branch\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06branch\x1a`\n" +
	"\rSkillsContext\x12O\n" +
	"\x10available_skills\x18\x01 \x03(\v2$.warp.multi_agent.v1.SkillDescriptorR\x0favailableSkills\x1ak\n" +
	"\x11LspServersContext\x12V\n" +
	"\x15available_lsp_servers\x18\x01 \x03(\v2\".warp.multi_agent.v1.LspDescriptorR\x13availableLspServersb\x06proto3"

var (
	file_input_context_proto_rawDescOnce sync.Once
	file_input_context_proto_rawDescData []byte
)

func file_input_context_proto_rawDescGZIP() []byte {
	file_input_context_proto_rawDescOnce.Do(func() {
		file_input_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_input_context_proto_rawDesc), len(file_input_context_proto_rawDesc)))
	})
	return file_input_context_proto_rawDescData
}

var file_input_context_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_input_context_proto_goTypes = []any{
	(*InputContext)(nil),                   // 0: warp.multi_agent.v1.InputContext
	(*InputContext_SelectedText)(nil),      // 1: warp.multi_agent.v1.InputContext.SelectedText
	(*InputContext_Directory)(nil),         // 2: warp.multi_agent.v1.InputContext.Directory
	(*InputContext_Shell)(nil),             // 3: warp.multi_agent.v1.InputContext.Shell
	(*InputContext_OperatingSystem)(nil),   // 4: warp.multi_agent.v1.InputContext.OperatingSystem
	(*InputContext_Image)(nil),             // 5: warp.multi_agent.v1.InputContext.Image
	(*InputContext_Codebase)(nil),          // 6: warp.multi_agent.v1.InputContext.Codebase
	(*InputContext_File)(nil),              // 7: warp.multi_agent.v1.InputContext.File
	(*InputContext_ProjectRules)(nil),      // 8: warp.multi_agent.v1.InputContext.ProjectRules
	(*InputContext_Git)(nil),               // 9: warp.multi_agent.v1.InputContext.Git
	(*InputContext_SkillsContext)(nil),     // 10: warp.multi_agent.v1.InputContext.SkillsContext
	(*InputContext_LspServersContext)(nil), // 11: warp.multi_agent.v1.InputContext.LspServersContext
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
	(*ExecutedShellCommand)(nil),           // 13: warp.multi_agent.v1.ExecutedShellCommand
	(*FileContent)(nil),                    // 14: warp.multi_agent.v1.FileContent
	(*SkillDescriptor)(nil),                // 15: warp.multi_agent.v1.SkillDescriptor
	(*LspDescriptor)(nil),                  // 16: warp.multi_agent.v1.LspDescriptor
}
var file_input_context_proto_depIdxs = []int32{
	2,  // 0: warp.multi_agent.v1.InputContext.directory:type_name -> warp.multi_agent.v1.InputContext.Directory
	4,  // 1: warp.multi_agent.v1.InputContext.operating_system:type_name -> warp.multi_agent.v1.InputContext.OperatingSystem
	3,  // 2: warp.multi_agent.v1.InputContext.shell:type_name -> warp.multi_agent.v1.InputContext.Shell
	12, // 3: warp.multi_agent.v1.InputContext.current_time:type_name -> google.protobuf.Timestamp
	6,  // 4: warp.multi_agent.v1.InputContext.codebases:type_name -> warp.multi_agent.v1.InputContext.Codebase
	8,  // 5: warp.multi_agent.v1.InputContext.project_rules:type_name -> warp.multi_agent.v1.InputContext.ProjectRules
	9,  // 6: warp.multi_agent.v1.InputContext.git:type_name -> warp.multi_agent.v1.InputContext.Git
	10, // 7: warp.multi_agent.v1.InputContext.updated_skills_context:type_name -> warp.multi_agent.v1.InputContext.SkillsContext
	11, // 8: warp.multi_agent.v1.InputContext.updated_lsp_servers_context:type_name -> warp.multi_agent.v1.InputContext.LspServersContext
	13, // 9: warp.multi_agent.v1.InputContext.executed_shell_commands:type_name -> warp.multi_agent.v1.ExecutedShellCommand
	1,  // 10: warp.multi_agent.v1.InputContext.selected_text:type_name -> warp.multi_agent.v1.InputContext.SelectedText
	5,  // 11: warp.multi_agent.v1.InputContext.images:type_name -> warp.multi_agent.v1.InputContext.Image
	7,  // 12: warp.multi_agent.v1.InputContext.files:type_name -> warp.multi_agent.v1.InputContext.File
	14, // 13: warp.multi_agent.v1.InputContext.File.content:type_name -> warp.multi_agent.v1.FileContent
	14, // 14: warp.multi_agent.v1.InputContext.ProjectRules.active_rule_files:type_name -> warp.multi_agent.v1.FileContent
	15, // 15: warp.multi_agent.v1.InputContext.SkillsContext.available_skills:type_name -> warp.multi_agent.v1.SkillDescriptor
	16, // 16: warp.multi_agent.v1.InputContext.LspServersContext.available_lsp_servers:type_name -> warp.multi_agent.v1.LspDescriptor
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_input_context_proto_init() }
func file_input_context_proto_init() {
	if File_input_context_proto != nil {
		return
	}
	file_file_content_proto_init()
	file_attachment_proto_init()
	file_options_proto_init()
	file_skill_proto_init()
	file_lsp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_input_context_proto_rawDesc), len(file_input_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_input_context_proto_goTypes,
		DependencyIndexes: file_input_context_proto_depIdxs,
		MessageInfos:      file_input_context_proto_msgTypes,
	}.Build()
	File_input_context_proto = out.File
	file_input_context_proto_goTypes = nil
	file_input_context_proto_depIdxs = nil
}
