// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: lsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A descriptor for an LSP server instance that the client can report as available.
type LspDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace root this server is associated with (repo/workspace path on the user's machine).
	WorkspaceRoot string `protobuf:"bytes,1,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	// The LSP server name (e.g. "rust-analyzer", "gopls", "pyright-langserver").
	ServerName    string `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LspDescriptor) Reset() {
	*x = LspDescriptor{}
	mi := &file_lsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LspDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LspDescriptor) ProtoMessage() {}

func (x *LspDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LspDescriptor.ProtoReflect.Descriptor instead.
func (*LspDescriptor) Descriptor() ([]byte, []int) {
	return file_lsp_proto_rawDescGZIP(), []int{0}
}

func (x *LspDescriptor) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *LspDescriptor) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

var File_lsp_proto protoreflect.FileDescriptor

const file_lsp_proto_rawDesc = "" +
	"\n" +
	"\tlsp.proto\x12\x13warp.multi_agent.v1\x1a\roptions.proto\"]\n" +
	"\rLspDescriptor\x12+\n" +
	"\x0eworkspace_root\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\rworkspaceRoot\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverNameb\x06proto3"

var (
	file_lsp_proto_rawDescOnce sync.Once
	file_lsp_proto_rawDescData []byte
)

func file_lsp_proto_rawDescGZIP() []byte {
	file_lsp_proto_rawDescOnce.Do(func() {
		file_lsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lsp_proto_rawDesc), len(file_lsp_proto_rawDesc)))
	})
	return file_lsp_proto_rawDescData
}

var file_lsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lsp_proto_goTypes = []any{
	(*LspDescriptor)(nil), // 0: warp.multi_agent.v1.LspDescriptor
}
var file_lsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lsp_proto_init() }
func file_lsp_proto_init() {
	if File_lsp_proto != nil {
		return
	}
	file_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lsp_proto_rawDesc), len(file_lsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_proto_goTypes,
		DependencyIndexes: file_lsp_proto_depIdxs,
		MessageInfos:      file_lsp_proto_msgTypes,
	}.Build()
	File_lsp_proto = out.File
	file_lsp_proto_goTypes = nil
	file_lsp_proto_depIdxs = nil
}
