// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: skill.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A complete descriptor of a skill without file content.
type SkillDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SkillReference:
	//
	//	*SkillDescriptor_Path
	//	*SkillDescriptor_BundledSkillId
	SkillReference isSkillDescriptor_SkillReference `protobuf_oneof:"skill_reference"`
	Name           string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Provider       *SkillDescriptor_Provider        `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Scope          *SkillDescriptor_Scope           `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SkillDescriptor) Reset() {
	*x = SkillDescriptor{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillDescriptor) ProtoMessage() {}

func (x *SkillDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillDescriptor.ProtoReflect.Descriptor instead.
func (*SkillDescriptor) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *SkillDescriptor) GetSkillReference() isSkillDescriptor_SkillReference {
	if x != nil {
		return x.SkillReference
	}
	return nil
}

func (x *SkillDescriptor) GetPath() string {
	if x != nil {
		if x, ok := x.SkillReference.(*SkillDescriptor_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *SkillDescriptor) GetBundledSkillId() string {
	if x != nil {
		if x, ok := x.SkillReference.(*SkillDescriptor_BundledSkillId); ok {
			return x.BundledSkillId
		}
	}
	return ""
}

func (x *SkillDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillDescriptor) GetProvider() *SkillDescriptor_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *SkillDescriptor) GetScope() *SkillDescriptor_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type isSkillDescriptor_SkillReference interface {
	isSkillDescriptor_SkillReference()
}

type SkillDescriptor_Path struct {
	// Path to the SKILL.md file defining this skill.
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type SkillDescriptor_BundledSkillId struct {
	// Unique identifier for a skill bundled with the client.
	BundledSkillId string `protobuf:"bytes,4,opt,name=bundled_skill_id,json=bundledSkillId,proto3,oneof"`
}

func (*SkillDescriptor_Path) isSkillDescriptor_SkillReference() {}

func (*SkillDescriptor_BundledSkillId) isSkillDescriptor_SkillReference() {}

// A lightweight reference to a skill.
// Unlike Skill, this does not include resolved metadata or file content.
type SkillRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SkillReference:
	//
	//	*SkillRef_Path
	//	*SkillRef_BundledSkillId
	SkillReference isSkillRef_SkillReference `protobuf_oneof:"skill_reference"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SkillRef) Reset() {
	*x = SkillRef{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRef) ProtoMessage() {}

func (x *SkillRef) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRef.ProtoReflect.Descriptor instead.
func (*SkillRef) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *SkillRef) GetSkillReference() isSkillRef_SkillReference {
	if x != nil {
		return x.SkillReference
	}
	return nil
}

func (x *SkillRef) GetPath() string {
	if x != nil {
		if x, ok := x.SkillReference.(*SkillRef_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *SkillRef) GetBundledSkillId() string {
	if x != nil {
		if x, ok := x.SkillReference.(*SkillRef_BundledSkillId); ok {
			return x.BundledSkillId
		}
	}
	return ""
}

type isSkillRef_SkillReference interface {
	isSkillRef_SkillReference()
}

type SkillRef_Path struct {
	// Path to the SKILL.md file defining this skill.
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type SkillRef_BundledSkillId struct {
	// Unique identifier for a skill bundled with the client.
	BundledSkillId string `protobuf:"bytes,2,opt,name=bundled_skill_id,json=bundledSkillId,proto3,oneof"`
}

func (*SkillRef_Path) isSkillRef_SkillReference() {}

func (*SkillRef_BundledSkillId) isSkillRef_SkillReference() {}

// A full representation of a skill, including file content.
// This should contain all the information necessary to recreate a ParsedSkill in the client.
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *SkillDescriptor       `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Content       *FileContent           `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{2}
}

func (x *Skill) GetDescriptor_() *SkillDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Skill) GetContent() *FileContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type SkillDescriptor_Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SkillDescriptor_Provider_Warp
	//	*SkillDescriptor_Provider_Agents
	//	*SkillDescriptor_Provider_Claude
	//	*SkillDescriptor_Provider_Codex
	//	*SkillDescriptor_Provider_Cursor
	//	*SkillDescriptor_Provider_Gemini
	//	*SkillDescriptor_Provider_Copilot
	//	*SkillDescriptor_Provider_Droid
	//	*SkillDescriptor_Provider_Github
	//	*SkillDescriptor_Provider_OpenCode
	Type          isSkillDescriptor_Provider_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillDescriptor_Provider) Reset() {
	*x = SkillDescriptor_Provider{}
	mi := &file_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillDescriptor_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillDescriptor_Provider) ProtoMessage() {}

func (x *SkillDescriptor_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillDescriptor_Provider.ProtoReflect.Descriptor instead.
func (*SkillDescriptor_Provider) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SkillDescriptor_Provider) GetType() isSkillDescriptor_Provider_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetWarp() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Warp); ok {
			return x.Warp
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetAgents() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Agents); ok {
			return x.Agents
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetClaude() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Claude); ok {
			return x.Claude
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetCodex() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Codex); ok {
			return x.Codex
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetCursor() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Cursor); ok {
			return x.Cursor
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetGemini() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Gemini); ok {
			return x.Gemini
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetCopilot() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Copilot); ok {
			return x.Copilot
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetDroid() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Droid); ok {
			return x.Droid
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetGithub() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_Github); ok {
			return x.Github
		}
	}
	return nil
}

func (x *SkillDescriptor_Provider) GetOpenCode() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Provider_OpenCode); ok {
			return x.OpenCode
		}
	}
	return nil
}

type isSkillDescriptor_Provider_Type interface {
	isSkillDescriptor_Provider_Type()
}

type SkillDescriptor_Provider_Warp struct {
	Warp *emptypb.Empty `protobuf:"bytes,1,opt,name=warp,proto3,oneof"`
}

type SkillDescriptor_Provider_Agents struct {
	Agents *emptypb.Empty `protobuf:"bytes,2,opt,name=agents,proto3,oneof"`
}

type SkillDescriptor_Provider_Claude struct {
	Claude *emptypb.Empty `protobuf:"bytes,3,opt,name=claude,proto3,oneof"`
}

type SkillDescriptor_Provider_Codex struct {
	Codex *emptypb.Empty `protobuf:"bytes,4,opt,name=codex,proto3,oneof"`
}

type SkillDescriptor_Provider_Cursor struct {
	Cursor *emptypb.Empty `protobuf:"bytes,5,opt,name=cursor,proto3,oneof"`
}

type SkillDescriptor_Provider_Gemini struct {
	Gemini *emptypb.Empty `protobuf:"bytes,6,opt,name=gemini,proto3,oneof"`
}

type SkillDescriptor_Provider_Copilot struct {
	Copilot *emptypb.Empty `protobuf:"bytes,7,opt,name=copilot,proto3,oneof"`
}

type SkillDescriptor_Provider_Droid struct {
	Droid *emptypb.Empty `protobuf:"bytes,8,opt,name=droid,proto3,oneof"`
}

type SkillDescriptor_Provider_Github struct {
	Github *emptypb.Empty `protobuf:"bytes,9,opt,name=github,proto3,oneof"`
}

type SkillDescriptor_Provider_OpenCode struct {
	OpenCode *emptypb.Empty `protobuf:"bytes,10,opt,name=open_code,json=openCode,proto3,oneof"`
}

func (*SkillDescriptor_Provider_Warp) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Agents) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Claude) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Codex) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Cursor) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Gemini) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Copilot) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Droid) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_Github) isSkillDescriptor_Provider_Type() {}

func (*SkillDescriptor_Provider_OpenCode) isSkillDescriptor_Provider_Type() {}

type SkillDescriptor_Scope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SkillDescriptor_Scope_Home
	//	*SkillDescriptor_Scope_Project
	//	*SkillDescriptor_Scope_Bundled
	Type          isSkillDescriptor_Scope_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillDescriptor_Scope) Reset() {
	*x = SkillDescriptor_Scope{}
	mi := &file_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillDescriptor_Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillDescriptor_Scope) ProtoMessage() {}

func (x *SkillDescriptor_Scope) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillDescriptor_Scope.ProtoReflect.Descriptor instead.
func (*SkillDescriptor_Scope) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SkillDescriptor_Scope) GetType() isSkillDescriptor_Scope_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SkillDescriptor_Scope) GetHome() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Scope_Home); ok {
			return x.Home
		}
	}
	return nil
}

func (x *SkillDescriptor_Scope) GetProject() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Scope_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *SkillDescriptor_Scope) GetBundled() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*SkillDescriptor_Scope_Bundled); ok {
			return x.Bundled
		}
	}
	return nil
}

type isSkillDescriptor_Scope_Type interface {
	isSkillDescriptor_Scope_Type()
}

type SkillDescriptor_Scope_Home struct {
	Home *emptypb.Empty `protobuf:"bytes,1,opt,name=home,proto3,oneof"`
}

type SkillDescriptor_Scope_Project struct {
	Project *emptypb.Empty `protobuf:"bytes,2,opt,name=project,proto3,oneof"`
}

type SkillDescriptor_Scope_Bundled struct {
	Bundled *emptypb.Empty `protobuf:"bytes,3,opt,name=bundled,proto3,oneof"`
}

func (*SkillDescriptor_Scope_Home) isSkillDescriptor_Scope_Type() {}

func (*SkillDescriptor_Scope_Project) isSkillDescriptor_Scope_Type() {}

func (*SkillDescriptor_Scope_Bundled) isSkillDescriptor_Scope_Type() {}

var File_skill_proto protoreflect.FileDescriptor

const file_skill_proto_rawDesc = "" +
	"\n" +
	"\vskill.proto\x12\x13warp.multi_agent.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12file_content.proto\"\xd9\a\n" +
	"\x0fSkillDescriptor\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12*\n" +
	"\x10bundled_skill_id\x18\x04 \x01(\tH\x00R\x0ebundledSkillId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12I\n" +
	"\bprovider\x18\x05 \x01(\v2-.warp.multi_agent.v1.SkillDescriptor.ProviderR\bprovider\x12@\n" +
	"\x05scope\x18\x06 \x01(\v2*.warp.multi_agent.v1.SkillDescriptor.ScopeR\x05scope\x1a\x85\x04\n" +
	"\bProvider\x12,\n" +
	"\x04warp\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x04warp\x120\n" +
	"\x06agents\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06agents\x120\n" +
	"\x06claude\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06claude\x12.\n" +
	"\x05codex\x18\x04 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05codex\x120\n" +
	"\x06cursor\x18\x05 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06cursor\x120\n" +
	"\x06gemini\x18\x06 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06gemini\x122\n" +
	"\acopilot\x18\a \x01(\v2\x16.google.protobuf.EmptyH\x00R\acopilot\x12.\n" +
	"\x05droid\x18\b \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05droid\x120\n" +
	"\x06github\x18\t \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06github\x125\n" +
	"\topen_code\x18\n" +
	" \x01(\v2\x16.google.protobuf.EmptyH\x00R\bopenCodeB\x06\n" +
	"\x04type\x1a\xa5\x01\n" +
	"\x05Scope\x12,\n" +
	"\x04home\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x04home\x122\n" +
	"\aproject\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\aproject\x122\n" +
	"\abundled\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\abundledB\x06\n" +
	"\x04typeB\x11\n" +
	"\x0fskill_reference\"_\n" +
	"\bSkillRef\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12*\n" +
	"\x10bundled_skill_id\x18\x02 \x01(\tH\x00R\x0ebundledSkillIdB\x11\n" +
	"\x0fskill_reference\"\x89\x01\n" +
	"\x05Skill\x12D\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2$.warp.multi_agent.v1.SkillDescriptorR\n" +
	"descriptor\x12:\n" +
	"\acontent\x18\x02 \x01(\v2 .warp.multi_agent.v1.FileContentR\acontentb\x06proto3"

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData []byte
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)))
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_skill_proto_goTypes = []any{
	(*SkillDescriptor)(nil),          // 0: warp.multi_agent.v1.SkillDescriptor
	(*SkillRef)(nil),                 // 1: warp.multi_agent.v1.SkillRef
	(*Skill)(nil),                    // 2: warp.multi_agent.v1.Skill
	(*SkillDescriptor_Provider)(nil), // 3: warp.multi_agent.v1.SkillDescriptor.Provider
	(*SkillDescriptor_Scope)(nil),    // 4: warp.multi_agent.v1.SkillDescriptor.Scope
	(*FileContent)(nil),              // 5: warp.multi_agent.v1.FileContent
	(*emptypb.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_skill_proto_depIdxs = []int32{
	3,  // 0: warp.multi_agent.v1.SkillDescriptor.provider:type_name -> warp.multi_agent.v1.SkillDescriptor.Provider
	4,  // 1: warp.multi_agent.v1.SkillDescriptor.scope:type_name -> warp.multi_agent.v1.SkillDescriptor.Scope
	0,  // 2: warp.multi_agent.v1.Skill.descriptor:type_name -> warp.multi_agent.v1.SkillDescriptor
	5,  // 3: warp.multi_agent.v1.Skill.content:type_name -> warp.multi_agent.v1.FileContent
	6,  // 4: warp.multi_agent.v1.SkillDescriptor.Provider.warp:type_name -> google.protobuf.Empty
	6,  // 5: warp.multi_agent.v1.SkillDescriptor.Provider.agents:type_name -> google.protobuf.Empty
	6,  // 6: warp.multi_agent.v1.SkillDescriptor.Provider.claude:type_name -> google.protobuf.Empty
	6,  // 7: warp.multi_agent.v1.SkillDescriptor.Provider.codex:type_name -> google.protobuf.Empty
	6,  // 8: warp.multi_agent.v1.SkillDescriptor.Provider.cursor:type_name -> google.protobuf.Empty
	6,  // 9: warp.multi_agent.v1.SkillDescriptor.Provider.gemini:type_name -> google.protobuf.Empty
	6,  // 10: warp.multi_agent.v1.SkillDescriptor.Provider.copilot:type_name -> google.protobuf.Empty
	6,  // 11: warp.multi_agent.v1.SkillDescriptor.Provider.droid:type_name -> google.protobuf.Empty
	6,  // 12: warp.multi_agent.v1.SkillDescriptor.Provider.github:type_name -> google.protobuf.Empty
	6,  // 13: warp.multi_agent.v1.SkillDescriptor.Provider.open_code:type_name -> google.protobuf.Empty
	6,  // 14: warp.multi_agent.v1.SkillDescriptor.Scope.home:type_name -> google.protobuf.Empty
	6,  // 15: warp.multi_agent.v1.SkillDescriptor.Scope.project:type_name -> google.protobuf.Empty
	6,  // 16: warp.multi_agent.v1.SkillDescriptor.Scope.bundled:type_name -> google.protobuf.Empty
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	file_file_content_proto_init()
	file_skill_proto_msgTypes[0].OneofWrappers = []any{
		(*SkillDescriptor_Path)(nil),
		(*SkillDescriptor_BundledSkillId)(nil),
	}
	file_skill_proto_msgTypes[1].OneofWrappers = []any{
		(*SkillRef_Path)(nil),
		(*SkillRef_BundledSkillId)(nil),
	}
	file_skill_proto_msgTypes[3].OneofWrappers = []any{
		(*SkillDescriptor_Provider_Warp)(nil),
		(*SkillDescriptor_Provider_Agents)(nil),
		(*SkillDescriptor_Provider_Claude)(nil),
		(*SkillDescriptor_Provider_Codex)(nil),
		(*SkillDescriptor_Provider_Cursor)(nil),
		(*SkillDescriptor_Provider_Gemini)(nil),
		(*SkillDescriptor_Provider_Copilot)(nil),
		(*SkillDescriptor_Provider_Droid)(nil),
		(*SkillDescriptor_Provider_Github)(nil),
		(*SkillDescriptor_Provider_OpenCode)(nil),
	}
	file_skill_proto_msgTypes[4].OneofWrappers = []any{
		(*SkillDescriptor_Scope_Home)(nil),
		(*SkillDescriptor_Scope_Project)(nil),
		(*SkillDescriptor_Scope_Bundled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
