// Common types used in request and response for the multi-agent API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: suggestions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suggestions struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Rules         []*SuggestedRule              `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Workflows     []*SuggestedAgentModeWorkflow `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestions) Reset() {
	*x = Suggestions{}
	mi := &file_suggestions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestions) ProtoMessage() {}

func (x *Suggestions) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestions.ProtoReflect.Descriptor instead.
func (*Suggestions) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{0}
}

func (x *Suggestions) GetRules() []*SuggestedRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Suggestions) GetWorkflows() []*SuggestedAgentModeWorkflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type SuggestedRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LoggingId     string                 `protobuf:"bytes,3,opt,name=logging_id,json=loggingId,proto3" json:"logging_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestedRule) Reset() {
	*x = SuggestedRule{}
	mi := &file_suggestions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestedRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedRule) ProtoMessage() {}

func (x *SuggestedRule) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedRule.ProtoReflect.Descriptor instead.
func (*SuggestedRule) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestedRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SuggestedRule) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SuggestedRule) GetLoggingId() string {
	if x != nil {
		return x.LoggingId
	}
	return ""
}

type SuggestedAgentModeWorkflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	LoggingId     string                 `protobuf:"bytes,3,opt,name=logging_id,json=loggingId,proto3" json:"logging_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestedAgentModeWorkflow) Reset() {
	*x = SuggestedAgentModeWorkflow{}
	mi := &file_suggestions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestedAgentModeWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedAgentModeWorkflow) ProtoMessage() {}

func (x *SuggestedAgentModeWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedAgentModeWorkflow.ProtoReflect.Descriptor instead.
func (*SuggestedAgentModeWorkflow) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestedAgentModeWorkflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SuggestedAgentModeWorkflow) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SuggestedAgentModeWorkflow) GetLoggingId() string {
	if x != nil {
		return x.LoggingId
	}
	return ""
}

var File_suggestions_proto protoreflect.FileDescriptor

const file_suggestions_proto_rawDesc = "" +
	"\n" +
	"\x11suggestions.proto\x12\x13warp.multi_agent.v1\"\x96\x01\n" +
	"\vSuggestions\x128\n" +
	"\x05rules\x18\x01 \x03(\v2\".warp.multi_agent.v1.SuggestedRuleR\x05rules\x12M\n" +
	"\tworkflows\x18\x02 \x03(\v2/.warp.multi_agent.v1.SuggestedAgentModeWorkflowR\tworkflows\"\\\n" +
	"\rSuggestedRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"logging_id\x18\x03 \x01(\tR\tloggingId\"g\n" +
	"\x1aSuggestedAgentModeWorkflow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"logging_id\x18\x03 \x01(\tR\tloggingIdb\x06proto3"

var (
	file_suggestions_proto_rawDescOnce sync.Once
	file_suggestions_proto_rawDescData []byte
)

func file_suggestions_proto_rawDescGZIP() []byte {
	file_suggestions_proto_rawDescOnce.Do(func() {
		file_suggestions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_suggestions_proto_rawDesc), len(file_suggestions_proto_rawDesc)))
	})
	return file_suggestions_proto_rawDescData
}

var file_suggestions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_suggestions_proto_goTypes = []any{
	(*Suggestions)(nil),                // 0: warp.multi_agent.v1.Suggestions
	(*SuggestedRule)(nil),              // 1: warp.multi_agent.v1.SuggestedRule
	(*SuggestedAgentModeWorkflow)(nil), // 2: warp.multi_agent.v1.SuggestedAgentModeWorkflow
}
var file_suggestions_proto_depIdxs = []int32{
	1, // 0: warp.multi_agent.v1.Suggestions.rules:type_name -> warp.multi_agent.v1.SuggestedRule
	2, // 1: warp.multi_agent.v1.Suggestions.workflows:type_name -> warp.multi_agent.v1.SuggestedAgentModeWorkflow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_suggestions_proto_init() }
func file_suggestions_proto_init() {
	if File_suggestions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_suggestions_proto_rawDesc), len(file_suggestions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suggestions_proto_goTypes,
		DependencyIndexes: file_suggestions_proto_depIdxs,
		MessageInfos:      file_suggestions_proto_msgTypes,
	}.Build()
	File_suggestions_proto = out.File
	file_suggestions_proto_goTypes = nil
	file_suggestions_proto_depIdxs = nil
}
