// TODO list types and operations for the multi-agent API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: todo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single TODO item.
type TodoItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the TODO item.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The title/summary of the TODO item.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Detailed description of the TODO item.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	mi := &file_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

func (x *TodoItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TodoItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Tool call to create a new TODO list.
type CreateTodoList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initial TODO items for the new list (optional).
	InitialTodos  []*TodoItem `protobuf:"bytes,1,rep,name=initial_todos,json=initialTodos,proto3" json:"initial_todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoList) Reset() {
	*x = CreateTodoList{}
	mi := &file_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoList) ProtoMessage() {}

func (x *CreateTodoList) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoList.ProtoReflect.Descriptor instead.
func (*CreateTodoList) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoList) GetInitialTodos() []*TodoItem {
	if x != nil {
		return x.InitialTodos
	}
	return nil
}

type UpdatePendingTodos struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UpdatedPendingTodos []*TodoItem            `protobuf:"bytes,1,rep,name=updated_pending_todos,json=updatedPendingTodos,proto3" json:"updated_pending_todos,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdatePendingTodos) Reset() {
	*x = UpdatePendingTodos{}
	mi := &file_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePendingTodos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePendingTodos) ProtoMessage() {}

func (x *UpdatePendingTodos) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePendingTodos.ProtoReflect.Descriptor instead.
func (*UpdatePendingTodos) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePendingTodos) GetUpdatedPendingTodos() []*TodoItem {
	if x != nil {
		return x.UpdatedPendingTodos
	}
	return nil
}

type MarkTodosCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodoIds       []string               `protobuf:"bytes,1,rep,name=todo_ids,json=todoIds,proto3" json:"todo_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTodosCompleted) Reset() {
	*x = MarkTodosCompleted{}
	mi := &file_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTodosCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTodosCompleted) ProtoMessage() {}

func (x *MarkTodosCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTodosCompleted.ProtoReflect.Descriptor instead.
func (*MarkTodosCompleted) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{3}
}

func (x *MarkTodosCompleted) GetTodoIds() []string {
	if x != nil {
		return x.TodoIds
	}
	return nil
}

var File_todo_proto protoreflect.FileDescriptor

const file_todo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"todo.proto\x12\x13warp.multi_agent.v1\"R\n" +
	"\bTodoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"T\n" +
	"\x0eCreateTodoList\x12B\n" +
	"\rinitial_todos\x18\x01 \x03(\v2\x1d.warp.multi_agent.v1.TodoItemR\finitialTodos\"g\n" +
	"\x12UpdatePendingTodos\x12Q\n" +
	"\x15updated_pending_todos\x18\x01 \x03(\v2\x1d.warp.multi_agent.v1.TodoItemR\x13updatedPendingTodos\"/\n" +
	"\x12MarkTodosCompleted\x12\x19\n" +
	"\btodo_ids\x18\x01 \x03(\tR\atodoIdsb\x06proto3"

var (
	file_todo_proto_rawDescOnce sync.Once
	file_todo_proto_rawDescData []byte
)

func file_todo_proto_rawDescGZIP() []byte {
	file_todo_proto_rawDescOnce.Do(func() {
		file_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)))
	})
	return file_todo_proto_rawDescData
}

var file_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_todo_proto_goTypes = []any{
	(*TodoItem)(nil),           // 0: warp.multi_agent.v1.TodoItem
	(*CreateTodoList)(nil),     // 1: warp.multi_agent.v1.CreateTodoList
	(*UpdatePendingTodos)(nil), // 2: warp.multi_agent.v1.UpdatePendingTodos
	(*MarkTodosCompleted)(nil), // 3: warp.multi_agent.v1.MarkTodosCompleted
}
var file_todo_proto_depIdxs = []int32{
	0, // 0: warp.multi_agent.v1.CreateTodoList.initial_todos:type_name -> warp.multi_agent.v1.TodoItem
	0, // 1: warp.multi_agent.v1.UpdatePendingTodos.updated_pending_todos:type_name -> warp.multi_agent.v1.TodoItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_todo_proto_init() }
func file_todo_proto_init() {
	if File_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_proto_goTypes,
		DependencyIndexes: file_todo_proto_depIdxs,
		MessageInfos:      file_todo_proto_msgTypes,
	}.Build()
	File_todo_proto = out.File
	file_todo_proto_goTypes = nil
	file_todo_proto_depIdxs = nil
}
